//

export const terms: string[] = [
	"standing",
	"bathroom",
	"sink",
	"inspired by Jacob More",
	"twitter",
	"reddit",
	"superflat",
	"front facing camera",
	"robot",
	"Nathan Fielder",
	"macbook",
	"slight color bleed",
	"Legolas",
	"tiktok",
	"frozen cold stare",
	"about 20 years old | short",
	"visa pour l'image",
	"selfie",
	"remote control",
	"inspired by John Button",
	"contest winner",
	"neogeo",
	"normal distributions",
	"big bold thick eyebrows",
	"tv frame",
	"at netflix",
	"eyelevel perspective image",
	"handyboy",
	"smiling",
	"rating",
	"general",
	"rotated",
	"glass of water",
	"inspired by Walter Bayes",
	"tumblr",
	"net art",
	"clean shaven",
	"french apartment",
	"f1 driver Charles Leclerc",
	"uncropped",
	"android format",
	"ikea",
	"generic male NPC face",
	"biohacking",
	"description",
	"kitchen",
	"looking at the camera",
	"deep tan skin",
	"hooked nose",
	"square jaw",
	"Sylas",
	"missing poster",
	"ultra wide camera",
	"Midsommar - T",
	"150mp",
	"Ian",
	"new",
	"facing sideways",
	"bad photo",
	"ice",
	"London",
	"GigaChad",
	"dazed and confused",
	"intimidated",
	"u-Tradetailed",
	"floor board",
	"album cover",
	"1950s",
	"1960s",
	"1970s",
	"1980s",
	"1990s",
	"2000s",
	"2010s",
	"2020s",
	"Bill Gates",
	"Jeff Bezos",
	"Marilyn Monroe",
	"George Clooney",
	"James Bond"
];
